# Generated by Django 5.1.1 on 2024-09-24 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaiaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('humidity', models.FloatField(max_length=4)),
                ('temperature', models.FloatField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('code', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('version', models.CharField(max_length=20)),
                ('sensor', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=50)),
                ('supports', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='WateringData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('meanHumidity', models.FloatField(max_length=4)),
                ('meanTemperature', models.FloatField(max_length=4)),
                ('wateringTime', models.IntegerField()),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gaiaApp.system')),
            ],
        ),
        migrations.DeleteModel(
            name='DataFactor',
        ),
        migrations.AddField(
            model_name='sensordata',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gaiaApp.system'),
        ),
    ]
