# Generated by Django 5.1.1 on 2024-09-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaiaApp', '0002_sensordata_system_wateringdata_delete_datafactor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
            ],
        ),
    ]
